from enum import Enum


class Intent(str, Enum):
    GET_PALKHI_LOCATION = "GET_PALKHI_LOCATION"
    GET_NEXT_HALT = "GET_NEXT_HALT"
    GET_NEXT_RINGAN = "GET_NEXT_RINGAN"
    GET_PALKHI_ROUTE = "GET_PALKHI_ROUTE"
    GET_NEAREST_MEDICAL = "GET_NEAREST_MEDICAL"
    REPORT_MISSING_PERSON = "REPORT_MISSING_PERSON"
    GENERAL_CONVERSATION = "GENERAL_CONVERSATION"
    UNKNOWN = "UNKNOWN"
